### ISSUE TITLE
Crashed with optifine

### ISSUE THREAD

**Issue by Spinoyonyx** [Cy4Shot/moai#1]
[crash-2021-05-10_12.44.27-server.txt](https://github.com/Cy4Shot/moai/files/6449553/crash-2021-05-10_12.44.27-server.txt)

When loading up a flat world i crashed

could be a tabula optifine issue but could be Moai aswell

**Comment by Cy4Shot** [comment]
Hi, thank you for submitting an issue.

Can you send me the mod list used?

**Comment by Spinoyonyx** [comment]
Tabula, ichuntil, xaeros world map, xaeros minimap, optifine,moai and jei thats all

**Comment by Cy4Shot** [comment]
> Tabula, ichuntil, xaeros world map, xaeros minimap, optifine,moai and jei thats all

can you try removing moai and seeing if the issue still persists?
