### ISSUE TITLE
Search Bar doesn't work

### ISSUE THREAD

**Issue by dark-gamer456** [Cy4Shot/moai#2]
When I try to type my model in the search bar, I do and nothing happens. I have no idea how to load the model. Do I need to add the .tbl at the end of the model name? Every model i try is in my mods/tabula/saves folder.

**Comment by Cy4Shot** [comment]
Nope, should search for the model by itself.... Show me the file strucutre where you saved them and the latest.log file located in the logs folder in minecraft.

**Comment by dark-gamer456** [comment]
[latest.log](https://github.com/Cy4Shot/moai/files/6642554/latest.log)
![Screenshot (250)](https://user-images.githubusercontent.com/85777064/121783149-f81f5000-cb61-11eb-99a7-033f0e419526.png)
